# Project: DXMan
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = obj/DXMan_private.res
OBJ  = obj/main.o $(RES)
LINKOBJ  = obj/main.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -mwindows -lmingw32 -lSDLmain -lSDL -lSDL_Mixer -lSDL_ttf  
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/include/SDL" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/include/SDL" 
BIN  = bin/DXMan.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS) -Dmain=SDL_main  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before bin/DXMan.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "bin\DXMan.exe" $(LIBS)

obj/main.o: main.c
	$(CPP) -c main.c -o obj/main.o $(CXXFLAGS)

obj/DXMan_private.res: DXMan_private.rc 
	$(WINDRES) -i DXMan_private.rc --input-format=rc -o obj/DXMan_private.res -O coff 
